apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: workflows
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: docker.io/vnadgir/hello-temporal
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure