apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: admintools
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.15.2
  name: temporal-admintools
  namespace: temporal
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app.kubernetes.io/component: admintools
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: temporal
    meta.helm.sh/release-namespace: temporal
  creationTimestamp: "2022-03-08T21:36:40Z"
  generation: 1
  labels:
    app.kubernetes.io/component: admintools
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.15.2
  name: temporal-admintools
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: admintools
      app.kubernetes.io/instance: temporal
      app.kubernetes.io/name: temporal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: admintools
        app.kubernetes.io/instance: temporal
        app.kubernetes.io/name: temporal
        app.kubernetes.io/part-of: temporal
        app.kubernetes.io/version: 1.15.2
    spec:
      containers:
      - env:
        - name: TEMPORAL_CLI_ADDRESS
          value: temporal-frontend:7233
        image: temporalio/admin-tools:1.15.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls
            - /
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: admin-tools
        ports:
        - containerPort: 22
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30